# Generated by Django 3.1.6 on 2021-04-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField(default='')),
                ('Descripcion', models.TextField(default='')),
                ('img', models.TextField(default='')),
                ('Nacionalidad', models.TextField(default='')),
                ('F_Muerte', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='DescripLib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('descrpicion', models.TextField(default='')),
                ('img', models.TextField(default='')),
                ('presio', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('descrpicion', models.TextField(default='')),
                ('img', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('descrpicion', models.TextField(default='')),
                ('img', models.TextField(default='')),
            ],
        ),
    ]
