# Generated by Django 3.1.6 on 2021-04-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20210412_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopers',
            name='genero',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
